apiVersion: v1
kind: Service
metadata:
  name: planning-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: planning-service
  ports:
    - port: 8002
      targetPort: 8000
