apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.advertised | quote }}
  REDIS_URL: "redis://redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST_CUSTOMER_USER: "customer-user-db.{{ .Release.Namespace }}.svc.cluster.local"
  POSTGRES_HOST_PLANNING: "planning-db.{{ .Release.Namespace }}.svc.cluster.local"
  POSTGRES_HOST_EXPENSE: "expense-db.{{ .Release.Namespace }}.svc.cluster.local"
  POSTGRES_PORT: "5432"
