apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB_CUSTOMER_USER: {{ .Values.postgres.dbCustomerUser | b64enc }}
  POSTGRES_DB_PLANNING: {{ .Values.postgres.dbPlanning | b64enc }}
  POSTGRES_DB_EXPENSE: {{ .Values.postgres.dbExpense | b64enc }}
  DATABASE_URL_CUSTOMER_USER: {{ printf "postgresql+asyncpg://%s:%s@customer-user-db.%s.svc.cluster.local:5432/%s" .Values.postgres.user .Values.postgres.password .Release.Namespace .Values.postgres.dbCustomerUser | b64enc }}
  DATABASE_URL_PLANNING: {{ printf "postgresql+asyncpg://%s:%s@planning-db.%s.svc.cluster.local:5432/%s" .Values.postgres.user .Values.postgres.password .Release.Namespace .Values.postgres.dbPlanning | b64enc }}
  DATABASE_URL_EXPENSE: {{ printf "postgresql+asyncpg://%s:%s@expense-db.%s.svc.cluster.local:5432/%s" .Values.postgres.user .Values.postgres.password .Release.Namespace .Values.postgres.dbExpense | b64enc }}
  GOOGLE_MAPS_API_KEY: {{ .Values.googleMapsApiKey | b64enc }}
  SECRET_KEY: {{ .Values.secretKey | b64enc }}
