apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: expense-service
  ports:
    - port: 8003
      targetPort: 8000
