apiVersion: v1
kind: Secret
metadata:
  name: svp-secret
  namespace: svp
type: Opaque
data:
  POSTGRES_USER: c3ZwX3VzZXI=
  POSTGRES_PASSWORD: c3ZwX3Bhc3M=
  POSTGRES_DB_CUSTOMER_USER: Y3VzdG9tZXJfdXNlcl9kYg==
  POSTGRES_DB_PLANNING: cGxhbm5pbmdfZGI=
  POSTGRES_DB_EXPENSE: ZXhwZW5zZV9kYg==
  DATABASE_URL_CUSTOMER_USER: cG9zdGdyZXNxbCthc3luY3BnOi8vc3ZwX3VzZXI6c3ZwX3Bhc3NAY3VzdG9tZXItdXNlci1kYi5zdnAuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9jdXN0b21lcl91c2VyX2Ri
  DATABASE_URL_PLANNING: cG9zdGdyZXNxbCthc3luY3BnOi8vc3ZwX3VzZXI6c3ZwX3Bhc3NAcGxhbm5pbmctZGIuc3ZwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcGxhbm5pbmdfZGI=
  DATABASE_URL_EXPENSE: cG9zdGdyZXNxbCthc3luY3BnOi8vc3ZwX3VzZXI6c3ZwX3Bhc3NAZXhwZW5zZS1kYi5zdnAuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9leHBlbnNlX2Ri
  GOOGLE_MAPS_API_KEY: cGxhY2Vob2xkZXI=
  SECRET_KEY: cGxhY2Vob2xkZXI=
