apiVersion: v1
kind: Service
metadata:
  name: customer-user-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: customer-user-service
  ports:
    - port: 8001
      targetPort: 8000
